"""Cloudflare Containers build plugin."""

from __future__ import annotations

import json

from pyflue.types import BuildContext, BuildPlugin


class CloudflarePlugin(BuildPlugin):
    """Build plugin for Cloudflare Workers + Containers.

    The generated Worker routes incoming requests to a Python container running
    PyFlue's FastAPI app. This gives PyFlue a deployable Cloudflare target while
    keeping the Python runtime intact.
    """

    name = "cloudflare"

    def generate_entry_point(self, ctx: BuildContext) -> str:
        return '''"""Auto-generated by pyflue build (cloudflare)."""
import os

from pyflue.server import create_app

app = create_app()

if __name__ == "__main__":
    import uvicorn
    port = int(os.getenv("PORT", "8000"))
    uvicorn.run(app, host="0.0.0.0", port=port)
'''

    def additional_outputs(self, ctx: BuildContext) -> dict[str, str]:
        return {
            "Dockerfile": """\
FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PYFLUE_MODE=production
ENV PORT=8000
EXPOSE 8000

CMD ["python", "server.py"]
""",
            "requirements.txt": """\
fastapi>=0.124.0,<1
uvicorn[standard]>=0.38.0,<1
pydantic>=2.12.2,<3
pyyaml>=6.0.2,<7
""",
            "worker.ts": _worker_ts(),
            "wrangler.jsonc": _wrangler_json(ctx),
            "package.json": _package_json(),
        }


def _worker_ts() -> str:
    return """\
import { Container } from "@cloudflare/containers";

export class PyFlueContainer extends Container {
  defaultPort = 8000;
  sleepAfter = "10m";
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);
    const routeKey = url.pathname.startsWith("/agents/")
      ? url.pathname.split("/").slice(0, 4).join("/")
      : "default";
    const container = env.PYFLUE_CONTAINER.getByName(routeKey);
    return container.fetch(request);
  },
};

interface Env {
  PYFLUE_CONTAINER: DurableObjectNamespace<PyFlueContainer> & {
    getByName(name: string): DurableObjectStub;
  };
}
"""


def _wrangler_json(ctx: BuildContext) -> str:
    return json.dumps(
        {
            "$schema": "node_modules/wrangler/config-schema.json",
            "name": "pyflue-agent",
            "main": "worker.ts",
            "compatibility_date": "2026-05-24",
            "containers": [
                {
                    "class_name": "PyFlueContainer",
                    "image": "./Dockerfile",
                    "max_instances": max(1, len(ctx.agents)),
                    "instance_type": "basic",
                }
            ],
            "durable_objects": {
                "bindings": [
                    {
                        "name": "PYFLUE_CONTAINER",
                        "class_name": "PyFlueContainer",
                    }
                ]
            },
            "migrations": [
                {
                    "tag": "v1",
                    "new_sqlite_classes": ["PyFlueContainer"],
                }
            ],
        },
        indent=2,
    ) + "\n"


def _package_json() -> str:
    return json.dumps(
        {
            "private": True,
            "type": "module",
            "scripts": {
                "dev": "wrangler dev",
                "deploy": "wrangler deploy",
            },
            "dependencies": {
                "@cloudflare/containers": "^0.0.19",
            },
            "devDependencies": {
                "typescript": "^5.0.0",
                "wrangler": "^4.0.0",
            },
        },
        indent=2,
    ) + "\n"
