"""Google Cloud Run build plugin."""

from __future__ import annotations

import json

from pyflue.types import BuildContext, BuildPlugin


class CloudRunPlugin(BuildPlugin):
    """Build plugin for Google Cloud Run.

    Generates a Dockerfile optimized for Cloud Run with gunicorn + uvicorn workers.
    """

    name = "cloudrun"

    def generate_entry_point(self, ctx: BuildContext) -> str:
        return '''"""Auto-generated by pyflue build (cloudrun)."""
import os

from pyflue.server import create_app

app = create_app()

if __name__ == "__main__":
    import uvicorn
    port = int(os.getenv("PORT", "8080"))
    uvicorn.run(
        "server:app",
        host="0.0.0.0",
        port=port,
        workers=int(os.getenv("WORKERS", "4")),
    )
'''

    def additional_outputs(self, ctx: BuildContext) -> dict[str, str]:
        return {
            "Dockerfile": """\
FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \\
    gcc \\
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PYFLUE_MODE=production
ENV PORT=8080

EXPOSE 8080

CMD ["gunicorn", "--bind", "0.0.0.0:8080", "--workers", "4", "--worker-class", "uvicorn.workers.UvicornWorker", "server:app"]
""",
            "requirements.txt": """\
fastapi>=0.115.0
uvicorn[standard]>=0.32.0
gunicorn>=23.0.0
pydantic>=2.0.0
pyyaml>=6.0
""",
            "cloudbuild.yaml": """\
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME']
images:
  - 'gcr.io/$PROJECT_ID/$REPO_NAME'
options:
  logging: CLOUD_LOGGING_ONLY
""",
        }


def _agent_var_name(name: str) -> str:
    import re
    safe = re.sub(r"[^a-zA-Z0-9_]", "_", name)
    return f"handler_{safe}"


def _json_dumps(data: dict) -> str:
    return json.dumps(data, indent=2)