"""Docker build plugin."""

from __future__ import annotations

from typing import Any

from pyflue.types import BuildContext, BuildPlugin


class DockerPlugin(BuildPlugin):
    """Build plugin for Docker containerized deployments.

    Generates a Dockerfile with gunicorn + uvicorn workers.
    """

    name = "docker"

    def generate_entry_point(self, ctx: BuildContext) -> str:
        return '''"""Auto-generated by pyflue build (docker)."""
import os

from pyflue.server import create_app

app = create_app()

if __name__ == "__main__":
    import uvicorn
    port = int(os.getenv("PORT", "8000"))
    uvicorn.run(
        app,
        host="0.0.0.0",
        port=port,
        workers=int(os.getenv("WORKERS", "4")),
    )
'''

    def additional_outputs(self, ctx: BuildContext) -> dict[str, str]:
        return {
            "Dockerfile": """\
FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

ENV PYFLUE_MODE=production

CMD ["python", "server.py"]
""",
            "requirements.txt": """\
fastapi>=0.115.0
uvicorn[standard]>=0.32.0
gunicorn>=23.0.0
pydantic>=2.0.0
pyyaml>=6.0
""",
            ".dockerignore": """\
__pycache__/
*.pyc
.pytest_cache/
.git/
.venv/
venv/
*.egg-info/
dist/
build/
""",
        }

    def esbuild_options(self, ctx: BuildContext) -> dict[str, Any]:
        return {}