"""AWS Lambda build plugin."""

from __future__ import annotations

from pyflue.types import BuildContext, BuildPlugin


class LambdaPlugin(BuildPlugin):
    """Build plugin for AWS Lambda with Mangum adapter.

    Generates a handler compatible with Lambda Function URL or API Gateway.
    """

    name = "lambda"

    def generate_entry_point(self, ctx: BuildContext) -> str:
        return '''"""Auto-generated by pyflue build (lambda)."""
try:
    from mangum import Mangum
except ImportError:
    raise ImportError("mangum is required. Install with: pip install mangum")

from pyflue.server import create_app


app = create_app()


handler = Mangum(app, lifespan="off")
'''

    def additional_outputs(self, ctx: BuildContext) -> dict[str, str]:
        requirements = """\
mangum>=0.17.0
fastapi>=0.115.0
uvicorn>=0.32.0
pydantic>=2.0.0
pyyaml>=6.0
"""
        return {"requirements.txt": requirements}
