"""Uvicorn/FastAPI build plugin."""

from __future__ import annotations

from pyflue.types import BuildContext, BuildPlugin


class UvicornPlugin(BuildPlugin):
    """Build plugin for Uvicorn + FastAPI servers.

    Uses the existing pyflue.server.create_app() function.
    """

    name = "uvicorn"

    def generate_entry_point(self, ctx: BuildContext) -> str:
        return '''"""Auto-generated by pyflue build (uvicorn)."""
import os

from pyflue.server import create_app

app = create_app()

if __name__ == "__main__":
    import uvicorn
    port = int(os.getenv("PORT", "8000"))
    uvicorn.run(app, host="0.0.0.0", port=port)
'''

    def additional_outputs(self, ctx: BuildContext) -> dict[str, str]:
        requirements = """\
fastapi>=0.115.0
uvicorn[standard]>=0.32.0
pydantic>=2.0.0
pyyaml>=6.0
"""
        return {"requirements.txt": requirements}