"""PyFlue public API."""

__version__ = "0.1.5"

from pyflue.client import PyFlueClient, create_flue_client, createFlueClient
from pyflue.config import define_config
from pyflue.core import PyFlueAgent, PyFlueFs, PyFlueSession, PyFlueSessions, init
from pyflue.harnesses.registry import register_harness
from pyflue.mcp import (
    MCPClient,
    McpServerConnection,
    McpStdioServerOptions,
    connect_mcp_server,
    connect_mcp_server_stdio,
)
from pyflue.routing import AgentRoute, PyFlueContext, discover_agent_routes
from pyflue.runs import (
    FlueRun,
    InMemoryRunRegistry,
    InMemoryRunStore,
    InstancePointer,
    RunEvent,
    RunPointer,
    SQLiteRunRegistry,
    SQLiteRunStore,
    decode_instance_cursor,
    decode_run_cursor,
    encode_instance_cursor,
    encode_run_cursor,
    generate_run_id,
    get_default_run_store,
    observe,
    unobserve,
)
from pyflue.search import BM25Search, SemanticSearch
from pyflue.skills import Role, Skill, load_roles, load_skills
from pyflue.tools import create_tools, createTools, define_tool
from pyflue.types import (
    AgentInfo,
    BuildContext,
    BuildOptions,
    BuildPlugin,
    CompactionConfig,
    McpConfig,
    McpMode,
    McpServerConfig,
    PromptCost,
    PromptImage,
    PromptModel,
    PromptResultResponse,
    PromptUsage,
    ProvidersConfig,
    ProviderSettings,
    PyFlueCommand,
    PyFlueConfig,
    PyFlueEvent,
    PyFlueEventCallback,
    ThinkingLevel,
    ToolDef,
    define_command,
)

__all__ = [
    "AgentInfo",
    "BuildContext",
    "BuildOptions",
    "BuildPlugin",
    "MCPClient",
    "McpConfig",
    "McpMode",
    "McpServerConfig",
    "McpServerConnection",
    "McpStdioServerOptions",
    "PyFlueAgent",
    "PyFlueClient",
    "createFlueClient",
    "create_flue_client",
    "PyFlueCommand",
    "PyFlueContext",
    "PyFlueEvent",
    "PyFlueEventCallback",
    "PyFlueFs",
    "PyFlueSession",
    "PyFlueSessions",
    "AgentRoute",
    "FlueRun",
    "InMemoryRunStore",
    "InMemoryRunRegistry",
    "InstancePointer",
    "RunEvent",
    "RunPointer",
    "SQLiteRunStore",
    "SQLiteRunRegistry",
    "decode_instance_cursor",
    "decode_run_cursor",
    "encode_instance_cursor",
    "encode_run_cursor",
    "generate_run_id",
    "get_default_run_store",
    "observe",
    "unobserve",
    "BM25Search",
    "CompactionConfig",
    "ProviderSettings",
    "ProvidersConfig",
    "PromptCost",
    "PromptImage",
    "PromptModel",
    "PromptResultResponse",
    "PromptUsage",
    "PyFlueConfig",
    "SemanticSearch",
    "Role",
    "Skill",
    "ThinkingLevel",
    "ToolDef",
    "connect_mcp_server",
    "connect_mcp_server_stdio",
    "createTools",
    "create_tools",
    "define_config",
    "discover_agent_routes",
    "define_command",
    "define_tool",
    "init",
    "load_roles",
    "load_skills",
    "register_harness",
]
